################### Moviebeat Configuration Example #########################

############################# Moviebeat ######################################

moviebeat:
  # Defines how often an event is sent to the output
  period: 10s

output.elasticsearch:
  # hosts: ["134.214.202.37:9200"]
  hosts: ["localhost:9200"]
#   index: 'moviebeat-%{+yyyy.MM.dd}'

# setup.template:
#   name: 'moviebeat'
#   pattern: 'moviebeat-*'
#   enabled: true
#   fields: "fields.yml"

setup.template.overwrite: true

output.elasticsearch.index: "moviebeat-%{[beat.version]}"
setup.template.name: "moviebeat"
setup.template.pattern: "moviebeat-*"

# setup.template.fields: "fields.yml"

# Path to fields.yml file to generate the template
# setup.template.fields: "fields.yml"
