################### Moviebeat Configuration Example #########################

############################# Moviebeat ######################################

moviebeat:
  # Defines how often an event is sent to the output
  period: 10s

output.elasticsearch:
  hosts: ["134.214.202.37:9200"]
#   index: 'moviebeat-%{+yyyy.MM.dd}'

# setup.template:
#   name: 'moviebeat'
#   pattern: 'moviebeat-*'
#   enabled: true
setup.template.fields: "fields.yml"
